h2 "Overview"
p -> "This is a MVC template for CoffeeScript, Express.js, Node.js and MySQL. The view engine is CoffeeKup. In this example code I try to demo a bit of everything: sessions, database, ajax, etc. Hopefully it will help people like myself to start."

h2 "Folders and Files"

h3 "Which file does what"
p -> "Usually you won't need to change these files except a few."
table ".guide_table",->
	tr ->
		td ".folder",-> "coffee_client/mvc.coffee"
		td -> "It handles JS debug flag for browser. For more info see the comments in config.coffee."
	tr ->
		td ".folder",-> "coffee_server/app.coffee"
		td -> "App wrapper. Add middle-wares."
	tr ->
		td ".folder",-> "coffee_server/config.coffee"
		td -> "App config file. Change those consts to your own."
	tr ->
		td ".folder",-> "coffee_server/mvc.coffee"
		td -> "A few debug function"
	tr ->
		td ".folder",-> "coffee_view/404.coffee"
		td -> "The view for 404 error."
	tr ->
		td ".folder",-> "coffee_view/500.coffee"
		td -> "The view for 500 error."
	tr ->
		td ".folder",-> "coffee_view/layout.coffee"
		td -> "The layout for all views."
	tr ->
		td ".folder",-> "Cakefile"
		td -> "For compiling CoffeeScript"
	tr ->
		td ".folder",-> "clear.sh"
		td -> "Shell to remove all example code from the template."
	tr ->
		td ".folder",-> "server.js"
		td -> "Another app wrapper. Don't touch."

h3 "Which folder to add files"
p -> "Usually you have to add files to those folders except \"gen\" and \"node_modules\""
table ".guide_table",->
	tr ->
		td ".folder",-> "coffee_client"
		td -> "Client-side CoffeeScript code here."
	tr ->
		td ".folder",-> "coffee_server"
		td -> "For server-side CoffeeScript code."
	tr ->
		td ".folder",-> "coffee_server/controller"
		td -> "Put your controller files here."
	tr ->
		td ".folder",-> "coffee_server/model"
		td -> "Put your model files here."
	tr ->
		td ".folder",-> "coffee_view"
		td -> "The view template. We use <a href='http://coffeekup.org/'>CoffeeKup</a> for our view engine."
	tr ->
		td ".folder",-> "coffee_view/view"
		td -> "Put your view files here"
	tr ->
		td ".folder",-> "coffee_view/partial"
		td -> "Put your partial view files here"
	tr ->
		td ".folder",-> "file_client"
		td -> "This folder is static which means it can be accessed from browser. Put your images/css/js file here."
	tr ->
		td ".folder",-> "file_server"
		td -> "This folder is server-side. It's like the coffee_server but the difference is that CoffeeScript files in this folder will not be compiled."
	tr ->
		td ".folder",-> "gen"
		td -> "A folder generated by CoffeeScript compiler. Don't touch anything here unless you are debugging. Files in this folder will be automatically overwritten."
	tr ->
		td ".folder",-> "node_modules"
		td -> "A folder for node module created by Node.js. Don't touch anything here."


h2 "Common Tasks"
h3 "Config the environments"
p -> "Express supports arbitrary environments, such as production, development or testing. Edit coffee_server/config.coffee to set config params." 

h3 "Add a new pair of controller/view"
p -> "A pair of controller/view should have exactly the same name. Create the controller file under coffee_server/controller folder and the view file under coffee_view folder. See the comments in coffee_server/controller/example.coffee"

h3 "Write clien-side CoffeeScript"
p -> "Create your files under coffee_client folder. They will be automatically compiled to JS and copied to gen/public_web folder."

h3 "Add 3rd party JS libraries"
p -> "Add the files to file_client/ (slient-side) or file_server/ (server-side)"

h2 "Some Examples"
h3 "Sessions"
p -> "The Login page demonstrate how to set a server-side session."
h3 "Partials"
p -> "In Express.js, partials are reusable View snippet. e.g. The partial \"db_setup_guide\" is used in both \"index\" and \"example\" View."
h3 "Ajax/Web Service"
p -> "Instead of rendering a view, a method can send JSON string only as well, which is convinient for creating API. The row deletion in the example is handled in this way. See the comments in coffee_server/controller/example.coffee"

h2 "Credits"
ol ->
	li ->"<a href='http://nodejs.org/'>NodeJS</a>"
	li -> "<a href='http://expressjs.com/'>Express.js</a>"
	li -> "<a href='http://jashkenas.github.com/coffee-script/'>CoffeeScript</a>"
	li -> "<a href='http://coffeekup.org/'>CoffeeKup</a>"
	li -> "Node.js module <a href='https://github.com/felixge/node-mysql'>node-mysql</a>"
	li -> "Node.js module <a href='https://github.com/Kijewski/node-mysql-pool'>node-mysql-pool</a>"
	li -> "Inspired by <a href='https://github.com/twilson63/express-coffee'>express-coffee</a>"
